<?php
$objectManager    = \Magento\Framework\App\ObjectManager::getInstance();
$carouselImages   = $objectManager->create('\Voicyou\Carousel\Model\Carousel')->getCollection()->setOrder('sort_order','ASC');
$carouselImageArr = $carouselImages->getData();
?>

<script type="text/javascript" xml="space">// 

    requirejs(['jquery', 'jquery.bootstrap'], function (jQuery, jQueryBootstrap) {
    });
 </script>
<div class="container">
<div id="myCarousel" class="carousel slide" data-ride="carousel"><!-- Indicators --><ol class="carousel-indicators">
<li class="active" data-target="#myCarousel" data-slide-to="0"></li>
<li data-target="#myCarousel" data-slide-to="1"></li>
<li data-target="#myCarousel" data-slide-to="2"></li>
</ol><!-- Wrapper for slides -->
<div class="carousel-inner">
    <?php 
        $i = 0;
        foreach($carouselImageArr as $carouselImg)
        { ?>
          <div class="item <?php if ($i == 0) echo 'active'; ?>"><img style="width: 100%;" src="pub/media/carousel/<?php echo $carouselImg['image_name'];  ?>" alt="Los Angeles" /></div>
    <?php 
        $i++;
        }
    ?>

</div>
<!-- Left and right controls --> <a class="left carousel-control" href="#myCarousel" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#myCarousel" data-slide="next"> <span class="glyphicon glyphicon-chevron-right"></span> <span class="sr-only">Next</span> </a></div>
</div>
